### ISSUE TITLE
NPE in `RetryHttpClient` line 146 after failing all retries (in `main` for 2.0.0)

### ISSUE THREAD

**Issue by tatu-at-datastax** [datastax/astra-db-java#33]
So, for a request that fails all retries (in this case Truncate Collection, that is, `deleteMany` with no filters), there's NPE due to no `Response` being available:

```
(NullPointerException) java.lang.NullPointerException: Cannot invoke "java.net.http.HttpResponse.body()" because "response" is null
java.lang.NullPointerException: Cannot invoke "java.net.http.HttpResponse.body()" because "response" is null
	at com.datastax.astra.internal.http.RetryHttpClient.parseHttpResponse(RetryHttpClient.java:146)
	at com.datastax.astra.internal.command.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:321)
	at com.datastax.astra.client.collections.Collection.deleteMany(Collection.java:1337)
	at com.datastax.astra.client.collections.Collection.deleteMany(Collection.java:1358)
	at com.datastax.astra.client.collections.Collection.deleteAll(Collection.java:1368)
	at com.datastax.stargate.perf.insertmany.entity.ItemCollection.deleteAll(ItemCollection.java:80)
	at com.datastax.stargate.perf.insertmany.InsertManyClient.validate(InsertManyClient.java:265)
	at com.datastax.stargate.perf.insertmany.InsertManyCollectionTest.call(InsertManyCollectionTest.java:59)
	at com.datastax.stargate.perf.insertmany.InsertManyCollectionTest.call(InsertManyCollectionTest.java:14)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
```

**Comment by clun** [comment]
If the request failed with a TIMEOUT the HTTP client is closing the thread and body is null.

Error management is now better:
```
com.datastax.astra.client.exceptions.DataAPITimeoutException: 
[TIMEOUT] - Timeout while executing command 'deleteMany' timeout: 10000 but was 10793
```

You can also extend the timeout for the operation you are interested in, default retry count is 1 = (no retry) 

```java
collection.deleteMany(new DeleteManyOptions().timeout(Duration.ofSeconds(30));
```

**Comment by tatu-at-datastax** [comment]
@clun I don't think this is yet fixed, saw it after rebuild.

**Comment by clun** [comment]
mmm Stil cannot reproduce, did i fix it when adding control to debug:

// Given

```java
// Position a retry count at 3 default is 1
HttpClientOptions httpClientOptions =  new HttpClientOptions()
  .retryCount(3)
  .retryDelay(Duration.ofMillis(100));
TableDeleteManyOptions deleteManyOptions = new TableDeleteManyOptions()
  .httpClientOptions(httpClientOptions)
  .timeout(Duration.ofMillis(10));  // <-- give impossible timeout to force it
t.deleteMany(null, deleteManyOptions);
```

Give me the expected logs
```
09:28:23.998 DEBUG com.datastax.astra.internal.command.AbstractCommandRunner : Running command: deleteMany
09:28:23.998 DEBUG com.datastax.astra.internal.command.AbstractCommandRunner : Overriding Http Client:
09:28:23.998 DEBUG com.datastax.astra.internal.command.AbstractCommandRunner : Overriding Timeouts to 10
09:28:24.013 ERROR com.datastax.astra.internal.http.RetryHttpClient : Failure on attempt 1/3 
09:28:24.013 ERROR com.datastax.astra.internal.http.RetryHttpClient : Failed request POST on http://localhost:8181/v1/default_keyspace/table_composite_pk
09:28:24.013 ERROR com.datastax.astra.internal.http.RetryHttpClient : + Exception was 
java.net.http.HttpTimeoutException: request timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:949)
        ...
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:160)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
09:28:24.124 ERROR com.datastax.astra.internal.http.RetryHttpClient : Failure on attempt 2/3 
09:28:24.125 ERROR com.datastax.astra.internal.http.RetryHttpClient : Failed request POST on http://localhost:8181/v1/default_keyspace/table_composite_pk
09:28:24.125 ERROR com.datastax.astra.internal.http.RetryHttpClient : + Exception was 
java.net.http.HttpTimeoutException: request timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:949)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
09:28:24.339 ERROR com.datastax.astra.internal.http.RetryHttpClient : Failure on attempt 3/3 
09:28:24.340 ERROR com.datastax.astra.internal.http.RetryHttpClient : Failed request POST on http://localhost:8181/v1/default_keyspace/table_composite_pk
09:28:24.340 ERROR com.datastax.astra.internal.http.RetryHttpClient : + Exception was 
java.net.http.HttpTimeoutException: request timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:949)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at com.datastax.astra.internal.http.RetryHttpClient.lambda$executeHttpRequest$1(RetryHttpClient.java:174)
	at com.evanlennick.retry4j.CallExecutor.tryCall(CallExecutor.java:133)
	at com.evanlennick.retry4j.CallExecutor.execute(CallExecutor.java:89)
	at com.evanlennick.retry4j.CallExecutor.execute(CallExecutor.java:60)
	at com.datastax.astra.internal.http.RetryHttpClient.executeHttpRequest(RetryHttpClient.java:184)
	at com.datastax.astra.internal.command.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:325)
	at com.datastax.astra.client.tables.Table.deleteMany(Table.java:942)
	at com.datastax.astra.test.integration.local.LocalTableITTest.should_delete_many(LocalTableITTest.java:496)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:767)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$8(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:156)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:146)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:144)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:160)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:146)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:144)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:160)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:146)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:144)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:100)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
09:28:24.340 ERROR com.datastax.astra.internal.http.RetryHttpClient : Calls failed after 3 retries
09:28:24.343 DEBUG com.datastax.astra.client.DataAPIClient : Command [deleteMany] with id [9c9374]
09:28:24.343 DEBUG com.datastax.astra.client.DataAPIClient : [9c9374][url]=http://localhost:8181/v1/default_keyspace/table_composite_pk
09:28:24.343 DEBUG com.datastax.astra.client.DataAPIClient : [9c9374][request]={"deleteMany":{}}
09:28:24.343 DEBUG com.datastax.astra.client.DataAPIClient : [9c9374][response-code]=0

com.datastax.astra.client.exceptions.DataAPITimeoutException: [TIMEOUT] - Timeout while executing command 'deleteMany' timeout: 10 but was 1340

	at com.datastax.astra.internal.command.AbstractCommandRunner.runCommand(AbstractCommandRunner.java:332)
	at com.datastax.astra.client.tables.Table.deleteMany(Table.java:942)
	at com.datastax.astra.test.integration.local.LocalTableITTest.should_delete_many(LocalTableITTest.java:496)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```
```

**Comment by tatu-at-datastax** [comment]
Ok that is odd. Maybe consider it fixed; I wonder if I didn't have latest fixes compiled or something.

**Comment by tatu-at-datastax** [comment]
Will close, assume I did something wrong as this can not be reproduced.
